name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    strategy:
      matrix:
        scala: [ 2.12.13, 2.13.5 ]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Setup scala ${{ matrix.scala }}
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path:
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Publish package
        run: sbt ++${{ matrix.scala }} publish
        env:
          GITHUB_USER: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
