name: Scala CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        scala: [2.13.13, 2.13.5]
        java: [adopt@1.8, adopt@1.11, adopt@1.15]


    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }} and Scala ${{ matrix.scala }}
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Compile
        run: sbt ++${{ matrix.scala }} test:compile
